### ISSUE TITLE
Can't run flow.run_local_server from a Docker container

### ISSUE THREAD

**Issue by ghost** [googleapis/google-auth-library-python-oauthlib#87] opened 2020-09-01 08:13 UTC
I am making a Flask API that I try to containerize. 

I am using the `google_auth_oauthlib` module to get the authorization from the user of my application to use his YouTube account.

This is performed in the `_get_authenticated_first_time` function of this [python file](https://github.com/lohiermichael/youtube-playlists-follow-up/blob/master/youtube_playlists_follow_up/src/authentication.py).
It works fine on my local server.

However, when I  am tying to containerize my application with Docker, the function `flow.run_local_server` runs forever without redirecting me anywhere.

I tried to pass as port argument of the `flow.run_local_server()` the value 8080 and map my local port 8080 to the port 8080 of the container in my [docker-compose.yaml](https://github.com/lohiermichael/youtube-playlists-follow-up/blob/master/docker-compose.yaml) file but it doesn't work either.

So my question is simple:
Do you know how to make a set up that allows to run the authentication flow inside a Docker container?

**Comment by kurtisvg** [comment] 2020-09-01 19:49
Hi @lohiermichael,

What's happening is that `flow.run_local_server()` is bound to `localhost` inside the container, which isn't accessible from outside the container (even if you publish the port). So what happens is traffic to your hosts `127.0.0.1` is forward to the container on `172.17.x.x`, but the server is listening on the guest `127.0.0.1`. Unfortunately I'm not aware of a great workaround for this - (@busunkim96 it might be nice to add `[an optional redirect_url arg to run_local_server()](https://github.com/googleapis/google-auth-library-python-oauthlib/blob/fb7fcd6cbecf8e6dbd94ae30b87b8e88e23de8e6/google_auth_oauthlib/flow.py#L456)` to allow for some more flexibility here)

Two alternatives:

1. Host's network interface directly (so that the host and guest have the same `127.0.0.1`) by passing `--net=host` from docker (looks like for docker-compose it might be `network_mode: "host"`)
2. You can try [`run_console()`](https://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.flow.html#google_auth_oauthlib.flow.InstalledAppFlow.run_console) instead, which asks the user to copy past the token into the console

**Comment by tswast** [comment] 2022-03-15 15:57
> You can try [run_console()](https://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.flow.html#google_auth_oauthlib.flow.InstalledAppFlow.run_console) instead, which asks the user to copy past the token into the console

This flow has been deprecated. https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html?m=1#disallowed-oob

**Comment by grbtm** [comment] 2022-05-20 10:18
Another option is to change the localhost assignment in /etc/hosts in the container to the container's IP (`hostname -i`). That will make the local server in the container listen to the container's `172.17.x.x` instead of `127.0.0.1`.

**Comment by gilesknap** [comment] 2022-05-21 08:53
I've made a PR to fix this #202 

Feature request is #201

**Comment by NickGreen99** [comment] 2022-06-30 16:12
@grbtm how would i do that without a docker-compose file?

**Comment by gilesknap** [comment] 2022-08-30 20:59
@Cliffstone Yes this works with the standard secret JSON with redirect URI as "http://localhost". 

If you call ``run_local_server()`` with ``bind_host=="0.0.0.0" then the server will listen on all the container's network adapters and will therefore see the redirect.

**Comment by Cliffstone** [comment] 2022-08-31 14:02
First, thank you for the contribution @gilesknap, I owe you a beer/equivalent 🍺  

I can confirm that this works, the mistake was on me. I needed to make sure the container was not using the "old" pip google-oauthlib package. To anyone persisting with this problem, running `python3 -m pip install git+https://github.com/googleapis/google-auth-library-python-oauthlib.git` from inside your container will fix it. 

I don't like the idea but until the changes reach downstream (pip) a temp fix could be to change the dockerfile so that it fetches the package from main rather than pip. To anyone having similar problems feel free to reach out to me...

**Comment by SShady97** [comment] 2022-09-24 03:37
> First, thank you for the contribution @gilesknap, I owe you a beer/equivalent 🍺
> 
> **I can confirm that this works**, the mistake was on me. I needed to make sure the container was not using the "old" pip google-oauthlib package. To anyone persisting with this problem, running `python3 -m pip install git+https://github.com/googleapis/google-auth-library-python-oauthlib.git` from inside your container will fix it.
> 
> I don't like the idea but until the changes reach downstream (pip) a temp fix could be to change the dockerfile so that it fetches the package from main rather than pip. To anyone having similar problems feel free to reach out to me...


You can help? I can't get it to work

**Comment by gilesknap** [comment] 2022-09-24 06:37
@SShady97 please describe the problem are you seeing?

**Comment by SShady97** [comment] 2022-09-25 00:24
I tried to do what cliffstone said by adding add "Run pip install git+https://github.com/googleapis/google-auth-library-python-oauthlib.git" in Dockerfile but i Keep getting "This site can't be reached. And according to your answer, I did not understand where to put bind_host=="0.0.0.0".

![image](https://user-images.githubusercontent.com/18180166/192123226-f80ffb2f-9277-4476-ba68-528c1b61a2a7.jpeg)

**Comment by gilesknap** [comment] 2022-09-25 16:04
Thanks for the details.

First off, the fix that I did is now in the latest release so you should be able to obtain it with:
```
pip install google-auth-oauthlib
``` 

To make the fix work you need to pass some extra parameters to run_local_server.

See my usage here https://github.com/gilesknap/gphotos-sync/blob/main/src/gphotos_sync/authorize.py#L78-L122

**Comment by SShady97** [comment] 2022-09-26 02:33
> Thanks for the details, @SShady97 .
> 
> 
> 
> First off, the fix that I did is now in the latest release so you should be able to obtain it with:
> 
> ```
> 
> pip install google-auth-oauthlib
> 
> ``` 
> 
> 
> 
> To make the fix work you need to pass some extra parameters to run_local_server.
> 
> 
> 
> See my usage here https://github.com/gilesknap/gphotos-sync/blob/main/src/gphotos_sync/authorize.py#L78-L122
> 
> 

Thanks, that fixed ir!

**Comment by gilesknap** [comment] 2023-01-19 08:24
I believe this can be closed as fixed in #202

**Comment by gboreczek** [comment] 2023-05-23 12:46
https://github.com/googleapis/google-auth-library-python-oauthlib/blob/b2e3688462ea9326afee2cae0f580857bc59b5f7/google_auth_oauthlib/flow.py#LL432C56-L432C60 can you edit also this line?

**Comment by gilesknap** [comment] 2023-05-23 15:22
The parameter `host` tells the function what redirect URL IP to use. If you are running in a container then the address you bind to would need to be 0.0.0.0 and you need to expose the port with `docker run -p8181:8181`. This means any clients connecting to your machine's IP on port 8181 would be directed to the container and the 0.0.0.0 means that the container auth service would accept that connection whatever IP it is directed to.

However, If you are not running the browser on the same machine then your authorisation keys would be going over the network un-encrypted. 

I believe for this reason the API is intended to use localhost only and OAuth almost certainly checks that (sorry I'd have to dig back into this to remind myself of the detail).

As it happens there is a manual hack that works - when the redirect gets an error, edit the browser URL to be your server IP instead of localhost. Its a hack and its insecure but it works because the edit is after OAuth has had sight of the request.

**Comment by gboreczek** [comment] 2023-05-24 09:57
Ok, now I understand. Thank you for this detailed explanation :).
Best regards!

**Closed** 2023-10-16 19:22 UTC
Labels: type: question
